### PR TITLE
Fix build errors observed with Bun

### PR DESCRIPTION
**Pull request by erdnaxe**
This pull requests proposes to fix multiple errors raised during a Bun build of CTFNote front. I believe most of these errors are due to an apollo version bump as bun is not using yarn.lock.

Definitely need an extra pair of eyes to check what I propose in https://github.com/TFNS/CTFNote/pull/233/commits/e07b82cea9f82dbf623353a8136f45cbda0811b7, I might have broken something.

### CODE REVIEW

**Comment by JJ-8** [comment]
Downstream I don't have any problems with building since the image I just published was created just fine: https://github.com/JJ-8/CTFNote/actions/runs/8020464483/job/21910366732
Maybe it is related to this commit that I don't have any issues: https://github.com/JJ-8/CTFNote/commit/f1f070c3014cab7dfbe0c3a26b7f8f3082801459 which freezes all the dependencies and add them to git to make CTFNote 'live forever'.

**Comment by JJ-8** [comment]
Hi @erdnaxe, can you try to use v3.0.0 and see if the problem still persist? If so, can you have a look at this again?

Commit https://github.com/TFNS/CTFNote/pull/233/commits/e07b82cea9f82dbf623353a8136f45cbda0811b7 should be merged anyway since it fixes an important deprecation notice.

**Comment by erdnaxe** [comment]
Dropped two commits that are no longer needed with v3.0.0 (thanks!).
I rebased and linted the fix for the deprecation.

**Comment by JJ-8** [comment]
Hey @erdnaxe, thank you for rebasing! I tested your branch but it gave me a white page on visit. I have looked into the error and fixed it on my side. I pushed this to your branch. Can you check if it works for you too? If so, this PR can be merged.

**Comment by JJ-8** [comment]
Hey @erdnaxe, I did not receive a response from you so I have updated your branch again with the main branch and tested it locally. It still works fine for me so I guess we can merge this. Thank you for your contribution!

**Pull request merged**
