### PR TITLE
Feature: iCal link

### PR DESCRIPTION
**Pull request by JJ-8**
This is a successor PR of https://github.com/TFNS/CTFNote/pull/146. I modified two things:
1. The UI for getting the link is changed: now you just click the button and the link is copied to your clipboard, confirmed with a checkmark.
2. The URL in the iCal is the URL for the CTF itself, not the link from CTFNote (as stated in https://github.com/TFNS/CTFNote/pull/146#issuecomment-1056452392).

Please note that this PR can NOT be merged before https://github.com/TFNS/CTFNote/pull/214 is merged because of the order of the migrations.

### CODE REVIEW

**Comment by JJ-8** [comment]
There were some merge conflicts with the `yarn.lock` files due to the new ical dependency. I have resolved them by removing the `yarn.lock` and running `yarn` again. This resulted in quite a big dependency update. I did a quick manual test of all the features and everything appears to still work fine.

**Comment by peace-maker** [comment]
@XeR Can you have a look please? ❤️ We'd like to use this feature!

**Review by XeR — CHANGES_REQUESTED** [review]
Nice PR, but… 😄 

I think we should not use a single shared token.
How do we invalidate a token when somebody leaves the team in bad terms?
Regenerating a token is doable, but it's a pain because everybody have to update everything.

What about `$id:$hash` instead ?
e.g. `?key=1337:deadbeefcafebabe…` with the hash being e.g. a SHA-1 of the password's hash

```
SELECT * FROM ctfnote_private."user" WHERE id = 42 AND encode(digest(password, 'sha1'), 'hex') = '851f5ebcbf8cf861f274b11b0ee1766db91bfd91';
 id | login |                           password                           |    role
----+-------+--------------------------------------------------------------+------------
 42 | XeR   | $2a$10$XXXXXXXXXXXXXXXXXXXXXXXXXXXX.XXXXXXXXXXXXXXXXXXXXXXXX | user_admin
(1 row)
```

I propose using SHA-1 because it is faster than MD5.
CRC-32 would be better, but I'm afraid some maniac would try to bruteforce it.

If we agree with my proposal, it means your PR needs the following changes:
- replace password with a "enable ical?" toggle in the admin interface
- replace the password with a boolean in the database
- change the verification logic

Keep in mind that this proposal might make it awkward when we implement #171.
We've been talking about that since 2020 (#20) so "whatever, we'll figure it out later" is a perfectly valid answer.

**Comment by JJ-8** [comment]
This is already included in https://github.com/TFNS/CTFNote/pull/237

**Pull request closed without merging**
