### PR TITLE
Fixing missing dependencies

### PR DESCRIPTION
**Pull request by takov751**
There was missing python from the api Docker image

### CODE REVIEW

**Comment by SakiiR** [comment]
Hi @takov751,

I removed my images and tried to bring everything up again and the build looks fine to me.

What was the issue with the missing dependencies ?

**Comment by XeR** [comment]
> I removed my images and tried to bring everything up again and the build looks fine to me.
> What was the issue with the missing dependencies ?

OP opened issue #3. I assume the issue is (only?) present in `arm64` but not `x86_64`.

@takov751 I took the liberty of pushing an additional commit to your branch.
Unfortunately, I do not have the required hardware to make sure the build still works on `arm64`.
Can you please test and report ?

**Review by XeR — APPROVED** [review]
Builds successfully on `x86_64`

**Review by takov751 — COMMENTED** [review]
Yes i should have just used that line to add dependencies

**Comment by takov751** [comment]
It builds on rpi4 now . I will make further tests , looks promising . However that these packages were missing from the node arm64 build is rather odd . Either way it's working. 😁

**Comment by takov751** [comment]
Wait i did closed this pull request , did I messed up . I am still learning git so I have probably messed up 🤔

**Review by takov751 — COMMENTED** [review]
Reviewed

**Comment by XeR** [comment]
>  However that these packages were missing from the node arm64 build is rather odd .

My guess is that, given the popularity of `x86_64` machines in the node ecosystem, most packages come with binaries/libraries pre-built for this platform.


> I am still learning git so I have probably messed up thinking

Ha ha, don't worry. git is pretty hard ;-)
https://en.wiktionary.org/wiki/git#Etymology_1


> Does that mean @SakiiR needs to approve it ? to merge it into the main repo ?

Approvals are not requirements to have a pull request merged. (c.f. #1)

**Pull request merged**
